[tool.poetry]
name = "my project init"
version = "0.1.0"
description = ""
authors = ["cchidalgog <ccamilo.hidalgo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
create = true
in-project = true